const AllCourses = [
  {
    id: 1,
    category: "photoshop",
    image: "../../images/thumbnails/photoshop-1.jpg",
    title: "ফটোশপ",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 2,
    category: "photoshop",
    image: "../../images/thumbnails/photoshop-2.jpg",
    title: "ফটোশপ",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 3,
    category: "photoshop",
    image: "../../images/thumbnails/photoshop-3.jpg",
    title: "ফটোশপ",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 4,
    category: "graphic",
    image: "../../images/thumbnails/graphic-design.jpg",
    title: "গ্রাফিক্স ডিজাইন",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 5,
    category: "adobe",
    image: "../../images/thumbnails/Illustrator-1.jpg",
    title: "অ্যাডোবি ইলাস্ট্রেটর",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 6,
    category: "adobe",
    image: "../../images/thumbnails/Illustrator-2.jpg",
    title: "অ্যাডোবি ইলাস্ট্রেটর",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 7,
    category: "webDesign",
    image: "../../images/thumbnails/photoshop-1.jpg",
    title: "ওয়েব ডিজাইন এন্ড ডেভেলপমেন্ট",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 8,
    category: "computer",
    image: "../../images/thumbnails/computer.jpg",
    title: "কম্পিউটার",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 9,
    category: "cpa",
    image: "../../images/thumbnails/cpa.jpg",
    title: "সিপিএ",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 10,
    category: "fiverr",
    image: "../../images/thumbnails/fiverr.jpg",
    title: "ফাইভার",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 11,
    category: "git",
    image: "../../images/thumbnails/git.jpg",
    title: "গিট",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 12,
    category: "googleAds",
    image: "../../images/thumbnails/google-ads.jpg",
    title: "গুগল এডস",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 13,
    category: "seo",
    image: "../../images/thumbnails/seo.jpg",
    title: "এসইও",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 14,
    category: "spokenEnglish",
    image: "../../images/thumbnails/spoken-english.jpg",
    title: "স্পকেন ইংলিশ",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 15,
    category: "wordpress",
    image: "../../images/thumbnails/wordpress-1.jpg",
    title: "ওয়ার্ডপ্রেস",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 16,
    category: "wordpress",
    image: "../../images/thumbnails/wordpress-2.jpg",
    title: "ওয়ার্ডপ্রেস",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  {
    id: 15,
    category: "wordpress",
    image: "../../images/thumbnails/wordpress-3.jpg",
    title: "ওয়ার্ডপ্রেস",
    des: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, dolor.",
    price: "৫০০ টাকা",
  },
  
];
